<?php

namespace Cierra\Auth\Services;

use Cierra\Auth\Contracts\TeamResolver;
use Illuminate\Contracts\Auth\Authenticatable;

/**
 * Default team resolver: replicates the legacy Jetstream-style behavior
 * the package shipped with prior to 0.4.0.
 *
 * Requires the host's User model to expose Jetstream-compatible methods
 * (`currentTeam`, `ownedTeams()`, `switchTeam()`) and a Team model at
 * `App\Models\Team` with `user_id` / `personal_team` columns.
 *
 * If your app does NOT match that shape, bind a different
 * \Cierra\Auth\Contracts\TeamResolver implementation in your service
 * container (see NullTeamResolver for a no-op variant).
 */
class JetstreamTeamResolver implements TeamResolver
{
    public function resolve(Authenticatable $user): Authenticatable
    {
        try {
            $team = $user->currentTeam ?? null;

            if (! $team) {
                $team = method_exists($user, 'ownedTeams')
                    ? $user->ownedTeams()->first()
                    : null;

                if (! $team) {
                    $team = $this->createTeam($user);
                }

                if (method_exists($user, 'switchTeam') && $team) {
                    $user->switchTeam($team);
                }
            }
        } catch (\Throwable $th) {
            logger()->warning('[cierra-auth] JetstreamTeamResolver failed: '.$th->getMessage());
        }

        return method_exists($user, 'fresh') ? ($user->fresh() ?? $user) : $user;
    }

    protected function createTeam(Authenticatable $user)
    {
        $teamClass = '\\App\\Models\\Team';

        if (! class_exists($teamClass)) {
            return null;
        }

        $data = [
            'user_id' => $user->getAuthIdentifier(),
            'name' => ($user->first_name ?? 'Default')."'s Team",
            'personal_team' => true,
        ];

        // Optional Botflow AccessGroup integration (kept for BC)
        $accessGroupClass = '\\Cierra\\LaravelBotflow\\Models\\AccessGroup';
        if (class_exists($accessGroupClass)) {
            $data['access_group_id'] = $accessGroupClass::create([
                'name' => ($user->first_name ?? 'Default')."'s Team",
                'description' => 'Default Access Group generated by App',
            ])->id;
        }

        if (! method_exists($user, 'ownedTeams')) {
            return null;
        }

        $user->ownedTeams()->save($teamClass::forceCreate($data));

        return $user->ownedTeams()->first();
    }
}
