<?php

namespace Cierra\Auth\Controllers;

use App\Models\Team;
use App\Models\User;
use Cierra\Auth\Auth;
use Illuminate\Support\Facades\Auth as FacadesAuth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class AuthController extends Controller
{
    public function login()
    {
        return redirect(Auth::getLoginUrl());
    }

    public function callback()
    {

        $code = request()->code;

        if (! $code) {
            return redirect()->route('cierra-auth.login');
        }

        $tokenRes = Http::post(config('cierra-auth-package.host').'/oauth/token', [
            'grant_type' => 'authorization_code',
            'client_id' => config('cierra-auth-package.client_id'),
            'client_secret' => config('cierra-auth-package.client_secret'),
            'redirect_uri' => route('cierra-auth.callback'),
            'code' => request()->code,
        ]);

        if (! $tokenRes->ok()) {
            return redirect()->route('cierra-auth.login');
        }

        $tokenRes = $tokenRes->json();

        if (! isset($tokenRes['access_token'])) {
            return redirect()->route('cierra-auth.login');
        }

        $token = $tokenRes['access_token'];

        // dd($token);
        //get user info
        $response = Http::withHeaders([
            'Authorization' => 'Bearer '.$token,
            'Accept' => 'application/json',
        ])->get(config('cierra-auth-package.host').'/api/user');

        // register app in admin panel, if the id is set in config
        if (config('cierra-auth-package.registers_app_id')) {
            Http::withHeaders([
                'Authorization' => 'Bearer '.$token,
                'Accept' => 'application/json',
            ])->post(config('cierra-auth-package.host').'/api/app/register', [
                'application_id' => config('cierra-auth-package.registers_app_id'),
            ]);
        }

        if (! $response->ok()) {
            throw new \Exception('Error getting user info');
        }

        $passportUser = $response->json();

        $userData = [
            'cierra_auth_id' => $passportUser['id'],
            'first_name' => $passportUser['first_name'],
            'last_name' => $passportUser['last_name'],
            'token' => $token,
            'refresh_token' => isset($tokenRes['refresh_token']) ? $tokenRes['refresh_token'] : null,
            'token_expires_in' => isset($tokenRes['expires_in']) ? now()->addSeconds($tokenRes['expires_in']) : null,
            'email_verified_at' => $passportUser['email_verified_at'],
        ];

        if (Schema::hasColumn('users', 'name')) {
            $userData['name'] = $passportUser['first_name'].' '.$passportUser['last_name'];
        }

        //if there is a password field, fill it with random string
        if (Schema::hasColumn('users', 'password')) {
            $userData['password'] = bcrypt(Str::random(16));
        }

        $user = User::updateOrCreate(
            [
                'email' => $passportUser['email'],
            ],
            $userData
        );

        $user = $this->handleUserTeams($user);

        FacadesAuth::guard('web')->login($user, true);

        return redirect(config('cierra-auth-package.redirect_after_login'));
    }

    protected function handleUserTeams(User $user): User
    {
        $team = $user->currentTeam;
        if (! $team) {
            $team = $user->ownedTeams()->first();
            if (! $team) {
                $team = $this->createTeam($user);
            }
            $user->switchTeam($team);
        }

        return $user->fresh();
    }

    protected function createTeam(User $user): void
    {
        $data = [
            'user_id' => $user->id,
            'name' => $user->first_name."'s Team",
            'personal_team' => true,
        ];

        // if class exists \Cierra\LaravelBotflow\Models\AccessGroup ->add access group to team
        if (class_exists('\Cierra\LaravelBotflow\Models\AccessGroup')) {
            $data['access_group_id'] = \Cierra\LaravelBotflow\Models\AccessGroup::create([
                'name' => $user->first_name."'s Team",
                'description' => 'Default Access Group generated by App',
            ])->id;
        }

        $user->ownedTeams()->save(Team::forceCreate($data));
    }

    public function logout()
    {

        FacadesAuth::logout();

        //config('cierra-auth-package.redirect_after_logout') is the url to redirect after logout, it may be path or domain+path, the final result should be a valid url like domain+path
        $redirectAfterLogout = config('cierra-auth-package.redirect_after_logout');

        //check if includes domain
        if (strpos($redirectAfterLogout, 'http') === false) {
            //if not, add domain
            $redirectAfterLogout = implode('/', [config('app.url'), $redirectAfterLogout]);
        }

        //remove // at the end of the url
        $redirectAfterLogout = rtrim($redirectAfterLogout, '/');

        // dd(config('cierra-auth-package.host').'/logout?redirect_after_logout='.$redirectAfterLogout);

        return redirect(config('cierra-auth-package.host').'/logout?redirect_after_logout='.$redirectAfterLogout);
    }
}
